//! The early-commit rule. Pure: tokens, token start
//! times and the previous decode's text in, one decision out.
//!
//! Fixtures `tests/fixtures/v2/commit-trace-*.json` are the arbiter. They were generated by a
//! Python prototype of this rule.

use crate::config::LatencyConfig;

/// Sentence-ending marks: a clause may end here when speech continues.
const END_MARKS: &str = "。？！?!";
/// Clause marks: a clause may end here once enough words precede them.
const SOFT_MARKS: &str = "，；,;";
/// Tokens that must follow a mark before it counts (shows the speaker kept going).
const MIN_TOKENS_AFTER: usize = 2;
/// Word tokens before a sentence-ending mark.
const MIN_TOKENS_BEFORE_END: usize = 2;
/// Wait cap: only look for a gap in this window before the last token.
const CAP_WINDOW_S: f64 = 2.0;
/// Wait cap: word tokens needed before the cut.
const CAP_MIN_TOKENS_BEFORE: usize = 4;
/// Cut this long before the token that starts the next clause.
pub const CUT_OFFSET_S: f64 = 0.06;
/// A committed clause is at least this long.
pub const MIN_CLAUSE_S: f64 = 0.1;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CommitSettings {
    pub comma_min_tokens: usize,
    pub stability: bool,
    pub split_long: bool,
    pub cap_tokens: usize,
}

impl From<&LatencyConfig> for CommitSettings {
    fn from(config: &LatencyConfig) -> Self {
        Self {
            comma_min_tokens: config.comma_min_tokens as usize,
            stability: config.stability,
            split_long: config.split_long,
            cap_tokens: config.cap_tokens as usize,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Decision {
    /// Nothing to commit; the decode's text becomes the next `prev_text`.
    None,
    /// A candidate exists but did not appear in the previous decode yet.
    WaitStable { k: usize },
    /// Cut after token `k` (punctuation commit).
    Commit { k: usize },
    /// Cut after token `k` (wait cap, no punctuation).
    Cap { k: usize },
}

impl Decision {
    pub fn cut_index(self) -> Option<usize> {
        match self {
            Self::Commit { k } | Self::Cap { k } => Some(k),
            Self::None | Self::WaitStable { .. } => None,
        }
    }
}

/// A recognizer token containing a CJK character, an ASCII letter or a digit.
pub fn is_word_token(token: &str) -> bool {
    token
        .chars()
        .any(|c| ('\u{4e00}'..='\u{9fff}').contains(&c) || c.is_ascii_alphanumeric())
}

/// True when the token is exactly one character and that character is in `set`.
fn single_char_in(token: &str, set: &str) -> bool {
    let mut chars = token.chars();
    matches!((chars.next(), chars.next()), (Some(c), None) if set.contains(c))
}

fn word_count(tokens: &[String]) -> usize {
    tokens.iter().filter(|t| is_word_token(t)).count()
}

/// Concatenate tokens the way the recognizer's text is built (English word starts carry a space).
pub fn join_tokens(tokens: &[String]) -> String {
    tokens.concat().trim().to_owned()
}

/// Decide whether the clause decoded as `tokens` (start times `times`, seconds from the clause
/// start) should be cut. `prev_text` is the previous decode's text for this clause.
pub fn decide(
    tokens: &[String],
    times: &[f64],
    prev_text: Option<&str>,
    settings: &CommitSettings,
) -> Decision {
    let n = tokens.len();
    let mut candidate = None;
    // Suffix counts make the scan linear: words after k, words before k.
    let mut after = word_count(tokens);
    let mut before = 0;
    for (k, token) in tokens.iter().enumerate() {
        if is_word_token(token) {
            after -= 1;
        }
        if after >= MIN_TOKENS_AFTER {
            let is_end = single_char_in(token, END_MARKS);
            let is_soft = single_char_in(token, SOFT_MARKS);
            if (is_end && before >= MIN_TOKENS_BEFORE_END)
                || (is_soft && before >= settings.comma_min_tokens)
            {
                candidate = Some(k);
            }
        }
        if is_word_token(token) {
            before += 1;
        }
    }
    if let Some(k) = candidate {
        let prefix = join_tokens(&tokens[..=k]);
        let stable = !settings.stability || prev_text.is_some_and(|prev| prev.starts_with(&prefix));
        return if stable {
            Decision::Commit { k }
        } else {
            Decision::WaitStable { k }
        };
    }
    if settings.split_long
        && settings.cap_tokens > 0
        && n >= 4
        && times.len() == n
        && word_count(tokens) >= settings.cap_tokens
    {
        let floor = times[n - 1] - CAP_WINDOW_S;
        let mut best: Option<(f64, usize)> = None;
        let mut words_through = 0;
        for k in 0..=n - 4 {
            if is_word_token(&tokens[k]) {
                words_through += 1;
            }
            if times[k] >= floor && words_through >= CAP_MIN_TOKENS_BEFORE {
                let gap = times[k + 1] - times[k];
                if best.is_none_or(|(widest, _)| gap > widest) {
                    best = Some((gap, k));
                }
            }
        }
        if let Some((_, k)) = best {
            return Decision::Cap { k };
        }
    }
    Decision::None
}

/// Seconds from the stream origin at which to cut: just before token `k + 1` starts, at least
/// `MIN_CLAUSE_S` into the clause and no later than the decoded audio end.
pub fn cut_at(clause_start_s: f64, next_token_time_s: f64, audio_end_s: f64) -> f64 {
    (clause_start_s + next_token_time_s - CUT_OFFSET_S)
        .max(clause_start_s + MIN_CLAUSE_S)
        .min(audio_end_s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn settings(stability: bool, comma: usize, cap: usize) -> CommitSettings {
        CommitSettings {
            comma_min_tokens: comma,
            stability,
            split_long: true,
            cap_tokens: cap,
        }
    }

    fn toks(text: &str) -> Vec<String> {
        text.chars().map(String::from).collect()
    }

    fn evenly(n: usize) -> Vec<f64> {
        (0..n).map(|i| i as f64 * 0.25).collect()
    }

    #[test]
    fn word_tokens_need_cjk_letters_or_digits() {
        for word in ["这", " school", "9", "bu", "Mate"] {
            assert!(is_word_token(word), "{word:?}");
        }
        for other in ["，", "。", " ", "", "?", "…"] {
            assert!(!is_word_token(other), "{other:?}");
        }
    }

    #[test]
    fn comma_needs_the_configured_number_of_words_before_it() {
        let t = toks("一二三四五六七，八九十");
        let s = evenly(t.len());
        // seven words before the comma
        assert_eq!(
            decide(
                &t,
                &s,
                Some("一二三四五六七，八九十"),
                &settings(true, 8, 0)
            ),
            Decision::None
        );
        let t = toks("一二三四五六七八，九十");
        let s = evenly(t.len());
        assert_eq!(
            decide(
                &t,
                &s,
                Some("一二三四五六七八，九十"),
                &settings(true, 8, 0)
            ),
            Decision::Commit { k: 8 }
        );
        assert_eq!(
            decide(
                &t,
                &s,
                Some("一二三四五六七八，九十"),
                &settings(true, 9, 0)
            ),
            Decision::None
        );
    }

    #[test]
    fn full_stop_needs_two_words_before_and_two_after() {
        let s = evenly(8);
        let ok = toks("你好吗。我很好");
        assert_eq!(
            decide(&ok, &evenly(ok.len()), None, &settings(false, 8, 0)),
            Decision::Commit { k: 3 }
        );
        let one_before = toks("好。我很好吧");
        assert_eq!(
            decide(&one_before, &s, None, &settings(false, 8, 0)),
            Decision::None
        );
        let one_after = toks("你好吗。我");
        assert_eq!(
            decide(&one_after, &s, None, &settings(false, 8, 0)),
            Decision::None
        );
    }

    #[test]
    fn largest_candidate_wins() {
        let t = toks("你好吗。我很好。你呢也是");
        let d = decide(&t, &evenly(t.len()), None, &settings(false, 8, 0));
        assert_eq!(d, Decision::Commit { k: 7 });
    }

    #[test]
    fn stability_requires_the_prefix_in_the_previous_decode() {
        let t = toks("你好吗。我很好");
        let s = evenly(t.len());
        assert_eq!(
            decide(&t, &s, None, &settings(true, 8, 0)),
            Decision::WaitStable { k: 3 }
        );
        assert_eq!(
            decide(&t, &s, Some("你好吗，我很"), &settings(true, 8, 0)),
            Decision::WaitStable { k: 3 }
        );
        assert_eq!(
            decide(&t, &s, Some("你好吗。我很"), &settings(true, 8, 0)),
            Decision::Commit { k: 3 }
        );
        assert_eq!(
            decide(&t, &s, None, &settings(false, 8, 0)),
            Decision::Commit { k: 3 }
        );
    }

    #[test]
    fn cap_cuts_at_the_widest_gap_in_the_last_two_seconds() {
        let t = toks("一二三四五六七八九十甲乙丙丁戊己庚辛壬癸子丑");
        let mut s: Vec<f64> = (0..t.len()).map(|i| i as f64 * 0.2).collect();
        // widest gap between tokens 14 and 15, inside the last 2 s
        for time in s.iter_mut().skip(15) {
            *time += 0.5;
        }
        let last = s[s.len() - 1];
        assert!(s[14] >= last - 2.0);
        assert_eq!(
            decide(&t, &s, None, &settings(true, 8, 20)),
            Decision::Cap { k: 14 }
        );
        // fewer word tokens than the cap: nothing
        assert_eq!(decide(&t, &s, None, &settings(true, 8, 25)), Decision::None);
        // cap off in either way
        assert_eq!(decide(&t, &s, None, &settings(true, 8, 0)), Decision::None);
        let off = CommitSettings {
            split_long: false,
            ..settings(true, 8, 20)
        };
        assert_eq!(decide(&t, &s, None, &off), Decision::None);
    }

    #[test]
    fn cap_without_a_usable_gap_does_nothing() {
        // every candidate k is before the 2 s window
        let t = toks("一二三四五六七八九十甲乙丙丁戊己庚辛壬癸");
        let mut s: Vec<f64> = (0..t.len()).map(|i| i as f64 * 0.01).collect();
        let n = s.len();
        s[n - 1] = 30.0;
        // k in 0..=n-4 have times far below 28
        assert_eq!(decide(&t, &s, None, &settings(true, 8, 20)), Decision::None);
    }

    #[test]
    fn cap_ties_pick_the_first_gap_and_need_four_words_before() {
        let t = toks("一二三四五六七八九十甲乙丙丁戊己庚辛壬癸");
        let s: Vec<f64> = (0..t.len()).map(|i| i as f64 * 0.25).collect();
        // all gaps are equal: the first k inside the last 2 s wins
        assert_eq!(
            decide(&t, &s, None, &settings(true, 8, 20)),
            Decision::Cap { k: 11 }
        );
    }

    #[test]
    fn cut_time_is_clamped() {
        assert!((cut_at(10.0, 2.0, 20.0) - 11.94).abs() < 1e-9);
        assert!((cut_at(10.0, 0.05, 20.0) - 10.1).abs() < 1e-9);
        assert!((cut_at(10.0, 5.0, 12.0) - 12.0).abs() < 1e-9);
    }

    fn string_list(value: &Value) -> Vec<String> {
        value
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_owned())
            .collect()
    }

    fn replay_trace(json: &str) -> usize {
        let trace: Value = serde_json::from_str(json).unwrap();
        let config = &trace["config"];
        let flag = |key: &str| config[key].as_str().unwrap().to_owned();
        let settings = CommitSettings {
            comma_min_tokens: flag("comma_min").parse().unwrap(),
            stability: flag("stable") == "1",
            split_long: true,
            cap_tokens: flag("cap").parse().unwrap(),
        };
        let mut checked = 0;
        for piece in trace["pieces"].as_array().unwrap() {
            for decode in piece["decodes"].as_array().unwrap() {
                let tokens = string_list(&decode["tokens"]);
                let times: Vec<f64> = decode["timestamps"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_f64().unwrap())
                    .collect();
                let prev = decode["prev_text"].as_str();
                let got = decide(&tokens, &times, prev, &settings);
                let expected = decode["decision"].as_str().unwrap();
                let name = match got {
                    Decision::None => "none",
                    Decision::WaitStable { .. } => "wait_stable",
                    Decision::Commit { .. } => "commit",
                    Decision::Cap { .. } => "cap",
                };
                assert_eq!(name, expected, "decode at {}", decode["audio_end"]);
                if let Some(k) = got.cut_index() {
                    assert_eq!(k as u64, decode["cut_index"].as_u64().unwrap());
                    let start = decode["clause_start"].as_f64().unwrap();
                    let audio_end = decode["audio_end"].as_f64().unwrap();
                    let at = cut_at(start, times[k + 1], audio_end);
                    let want = decode["cut_at"].as_f64().unwrap();
                    assert!((at - want).abs() <= 0.001, "cut {at} vs {want}");
                    assert_eq!(
                        join_tokens(&tokens[..=k]),
                        decode["prefix"].as_str().unwrap()
                    );
                    assert_eq!(
                        join_tokens(&tokens[k + 1..]),
                        decode["tail"].as_str().unwrap()
                    );
                }
                checked += 1;
            }
        }
        checked
    }

    #[test]
    fn juan_clip_trace_is_reproduced() {
        let n = replay_trace(include_str!("../tests/fixtures/v2/commit-trace-juan.json"));
        assert!(n > 40, "{n}");
    }

    #[test]
    fn juan_clip_with_the_cap_is_reproduced() {
        let n = replay_trace(include_str!(
            "../tests/fixtures/v2/commit-trace-juan-cap20.json"
        ));
        assert!(n > 40, "{n}");
    }

    #[test]
    fn conversation_trace_is_reproduced() {
        let n = replay_trace(include_str!(
            "../tests/fixtures/v2/commit-trace-conv60.json"
        ));
        assert!(n > 40, "{n}");
    }

    #[test]
    fn keynote_trace_is_reproduced() {
        let n = replay_trace(include_str!(
            "../tests/fixtures/v2/commit-trace-keynote60.json"
        ));
        assert!(n > 40, "{n}");
    }
}
